"""
This class contains buttons styles which will can be applied
"""


class Style:
    style_btn_selected_home = (u"QPushButton{\n"
                               "background-image: url(:/icons/homeIcon.png);\n"
                               "background-position: left center;\n"
                               "background-repeat: no-repeat;\n"
                               "border: none;\n"
                               "border-left: 14px solid rgb(122, 100, 189);\n"
                               "text-align: left;\n"
                               "padding-left: 45px;\n"
                               "background-color: rgb(122, 100, 189);\n"
                               "\n"
                               "\n"
                               "\n"
                               "}\n"
                               "QPushButton:hover{\n"
                               "	\n"
                               "	background-color: rgb(122, 100, 189);\n"
                               "	border-left: 14px solid rgb(122, 100, 189);\n"
                               "}\n"
                               "\n"
                               "QPushButton:pressed {\n"
                               "	background-color: rgb(211, 201, 242);\n"
                               "    border-left: 14px solid rgb(211, 201, 242);\n"
                               "}\n"
                               "\n"
                               "")

    style_btn_default_home = (u"QPushButton{\n"
                              "background-image: url(:/icons/homeIcon.png);\n"
                              "background-position: left center;\n"
                              "background-repeat: no-repeat;\n"
                              "border: none;\n"
                              "border-left: 14px solid rgb(155, 127, 240);\n"
                              "text-align: left;\n"
                              "padding-left: 45px;\n"
                              "background-color: rgb(155, 127, 240);\n"
                              "\n"
                              "\n"
                              "\n"
                              "}\n"
                              "QPushButton:hover{\n"
                              "	\n"
                              "	background-color: rgb(122, 100, 189);\n"
                              "	border-left: 14px solid rgb(122, 100, 189);\n"
                              "}\n"
                              "\n"
                              "QPushButton:pressed {\n"
                              "	background-color: rgb(211, 201, 242);\n"
                              "    border-left: 14px solid rgb(211, 201, 242);\n"
                              "}\n"
                              "\n"
                              "")

    style_btn_selected_food = (u"QPushButton{\n"
                               "background-image: url(:/icons/food.png);\n"
                               "background-position: left center;\n"
                               "background-repeat: no-repeat;\n"
                               "border: none;\n"
                               "border-left: 14px solid rgb(122, 100, 189);\n"
                               "text-align: left;\n"
                               "padding-left: 45px;\n"
                               "background-color: rgb(122, 100, 189);\n"
                               "\n"
                               "\n"
                               "\n"
                               "}\n"
                               "QPushButton:hover{\n"
                               "	\n"
                               "	background-color: rgb(122, 100, 189);\n"
                               "	border-left: 14px solid rgb(122, 100, 189);\n"
                               "}\n"
                               "\n"
                               "QPushButton:pressed {\n"
                               "	background-color: rgb(211, 201, 242);\n"
                               "    border-left: 14px solid rgb(211, 201, 242);\n"
                               "}")

    style_btn_default_food = (u"QPushButton{\n"
                              "background-image: url(:/icons/food.png);\n"
                              "background-position: left center;\n"
                              "background-repeat: no-repeat;\n"
                              "border: none;\n"
                              "border-left: 14px solid rgb(155, 127, 240);\n"
                              "text-align: left;\n"
                              "padding-left: 45px;\n"
                              "background-color: rgb(155, 127, 240);\n"
                              "\n"
                              "\n"
                              "\n"
                              "}\n"
                              "QPushButton:hover{\n"
                              "	\n"
                              "	background-color: rgb(122, 100, 189);\n"
                              "	border-left: 14px solid rgb(122, 100, 189);\n"
                              "}\n"
                              "\n"
                              "QPushButton:pressed {\n"
                              "	background-color: rgb(211, 201, 242);\n"
                              "    border-left: 14px solid rgb(211, 201, 242);\n"
                              "}")

    style_btn_selected_statistic = (u"QPushButton{\n"
                                    "background-image: url(:/icons/statisticIcon.png);\n"
                                    "background-position: left center;\n"
                                    "background-repeat: no-repeat;\n"
                                    "border: none;\n"
                                    "border-left: 14px solid rgb(122, 100, 189);\n"
                                    "text-align: left;\n"
                                    "padding-left: 45px;\n"
                                    "background-color: rgb(122, 100, 189);\n"
                                    "\n"
                                    "\n"
                                    "\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "	\n"
                                    "	background-color: rgb(122, 100, 189);\n"
                                    "	border-left: 14px solid rgb(122, 100, 189);\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:pressed {\n"
                                    "	background-color: rgb(211, 201, 242);\n"
                                    "    border-left: 14px solid rgb(211, 201, 242);\n"
                                    "}")

    style_btn_default_statistic = (u"QPushButton{\n"
                                   "background-image: url(:/icons/statisticIcon.png);\n"
                                   "background-position: left center;\n"
                                   "background-repeat: no-repeat;\n"
                                   "border: none;\n"
                                   "border-left: 14px solid rgb(155, 127, 240);\n"
                                   "text-align: left;\n"
                                   "padding-left: 45px;\n"
                                   "background-color: rgb(155, 127, 240);\n"
                                   "\n"
                                   "\n"
                                   "\n"
                                   "}\n"
                                   "QPushButton:hover{\n"
                                   "	\n"
                                   "	background-color: rgb(122, 100, 189);\n"
                                   "	border-left: 14px solid rgb(122, 100, 189);\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton:pressed {\n"
                                   "	background-color: rgb(211, 201, 242);\n"
                                   "    border-left: 14px solid rgb(211, 201, 242);\n"
                                   "}")

    style_btn_selected_statistic = (u"QPushButton{\n"
                                    "background-image: url(:/icons/statisticIcon.png);\n"
                                    "background-position: left center;\n"
                                    "background-repeat: no-repeat;\n"
                                    "border: none;\n"
                                    "border-left: 14px solid rgb(122, 100, 189);\n"
                                    "text-align: left;\n"
                                    "padding-left: 45px;\n"
                                    "background-color: rgb(122, 100, 189);\n"
                                    "\n"
                                    "\n"
                                    "\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "	\n"
                                    "	background-color: rgb(122, 100, 189);\n"
                                    "	border-left: 14px solid rgb(122, 100, 189);\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:pressed {\n"
                                    "	background-color: rgb(211, 201, 242);\n"
                                    "    border-left: 14px solid rgb(211, 201, 242);\n"
                                    "}")

    style_btn_default_calendar = (u"QPushButton{\n"
                                   "background-image: url(:/icons/calemdarIcon.png);\n"
                                   "background-position: left center;\n"
                                   "background-repeat: no-repeat;\n"
                                   "border: none;\n"
                                   "border-left: 14px solid rgb(155, 127, 240);\n"
                                   "text-align: left;\n"
                                   "padding-left: 45px;\n"
                                   "background-color: rgb(155, 127, 240);\n"
                                   "\n"
                                   "\n"
                                   "\n"
                                   "}\n"
                                   "QPushButton:hover{\n"
                                   "	\n"
                                   "	background-color: rgb(122, 100, 189);\n"
                                   "	border-left: 14px solid rgb(122, 100, 189);\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton:pressed {\n"
                                   "	background-color: rgb(211, 201, 242);\n"
                                   "    border-left: 14px solid rgb(211, 201, 242);\n"
                                   "}")

    style_btn_selected_calendar = (u"QPushButton{\n"
                                   "background-image: url(:/icons/calemdarIcon.png);\n"
                                   "background-position: left center;\n"
                                   "background-repeat: no-repeat;\n"
                                   "border: none;\n"
                                   "border-left: 14px solid rgb(122, 100, 189);\n"
                                   "text-align: left;\n"
                                   "padding-left: 45px;\n"
                                   "background-color: rgb(122, 100, 189);\n"
                                   "\n"
                                   "\n"
                                   "\n"
                                   "}\n"
                                   "QPushButton:hover{\n"
                                   "	\n"
                                   "	background-color: rgb(122, 100, 189);\n"
                                   "	border-left: 14px solid rgb(122, 100, 189);\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton:pressed {\n"
                                   "	background-color: rgb(211, 201, 242);\n"
                                   "    border-left: 14px solid rgb(211, 201, 242);\n"
                                   "}")

    style_btn_default_settings = (u"QPushButton{\n"
                                  "background-image: url(:/icons/settingsIcon.png);\n"
                                  "background-position: left center;\n"
                                  "background-repeat: no-repeat;\n"
                                  "border: none;\n"
                                  "border-left: 14px solid rgb(155, 127, 240);\n"
                                  "text-align: left;\n"
                                  "padding-left: 45px;\n"
                                  "background-color: rgb(155, 127, 240);\n"
                                  "\n"
                                  "\n"
                                  "\n"
                                  "}\n"
                                  "QPushButton:hover{\n"
                                  "	\n"
                                  "	background-color: rgb(122, 100, 189);\n"
                                  "	border-left: 14px solid rgb(122, 100, 189);\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:pressed {\n"
                                  "	background-color: rgb(211, 201, 242);\n"
                                  "    border-left: 14px solid rgb(211, 201, 242);\n"
                                  "}")



    style_btn_selected_stat_controle = (u"QPushButton{\n"
                                        "	background-color: rgb(122, 100, 189);\n"
                                        "	border-radius: 15px;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "	background-color: rgb(122, 100, 189);\n"
                                        "	border-radius: 15px;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "	background-color: rgb(211, 201, 242);\n"
                                        "	border-radius: 15px;\n"
                                        "}\n"
                                        "")

    style_btn_default_general_stat_control = (u"QPushButton{\n"
                                              "	background-color: rgb(155, 127, 240);\n"
                                              "	border-radius: 15px;\n"
                                              "}\n"
                                              "QPushButton:hover{\n"
                                              "	background-color: rgb(122, 100, 189);\n"
                                              "	border-radius: 15px;\n"
                                              "}\n"
                                              "\n"
                                              "QPushButton:pressed {\n"
                                              "	background-color: rgb(211, 201, 242);\n"
                                              "	border-radius: 15px;\n"
                                              "}\n"
                                              "")
