"""
This class contains buttons styles which will can be applied
"""


class Style():
    style_btn_clicked_settings = (u"QPushButton{\n"
                                  "background-image: url(:/icons/settingsIcon.png);\n"
                                  "background-position: left center;\n"
                                  "background-repeat: no-repeat;\n"
                                  "border: none;\n"
                                  "border-left: 14px solid rgb(65, 43, 173);\n"
                                  "text-align: left;\n"
                                  "padding-left: 45px;\n"
                                  "background-color: rgb(65, 43, 173);\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:hover{\n"
                                  "   background-color: rgb(65, 43, 173);\n"
                                  "   border-left: 14px solid rgb(65, 43, 173);\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:pressed {\n"
                                  "      background-color: rgb(155, 127, 240);\n"
                                  "        border-left: 14px solid rgb(155, 127, 240);\n"
                                  "}")

    style_btn_clicked_food = (u"QPushButton{\n"
                              "background-image: url(:/icons/food.png);\n"
                              "background-position: left center;\n"
                              "background-repeat: no-repeat;\n"
                              "border: none;\n"
                              "border-left: 14px solid rgb(65, 43, 173);\n"
                              "text-align: left;\n"
                              "padding-left: 45px;\n"
                              "background-color: rgb(65, 43, 173);\n"
                              "}\n"
                              "\n"
                              "QPushButton:hover{\n"
                              "   background-color: rgb(65, 43, 173);\n"
                              "   border-left: 14px solid rgb(65, 43, 173);\n"
                              "}\n"
                              "\n"
                              "QPushButton:pressed {\n"
                              "      background-color: rgb(155, 127, 240);\n"
                              "        border-left: 14px solid rgb(155, 127, 240);\n"
                              "}")

    style_btn_clicked_statistic = (u"QPushButton{\n"
                                   "background-image: url(:/icons/statisticIcon.png);\n"
                                   "background-position: left center;\n"
                                   "background-repeat: no-repeat;\n"
                                   "border: none;\n"
                                   "border-left: 14px solid rgb(65, 43, 173);\n"
                                   "text-align: left;\n"
                                   "padding-left: 45px;\n"
                                   "background-color: rgb(65, 43, 173);\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton:hover{\n"
                                   "   background-color: rgb(65, 43, 173);\n"
                                   "   border-left: 14px solid rgb(65, 43, 173);\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton:pressed {\n"
                                   "      background-color: rgb(155, 127, 240);\n"
                                   "        border-left: 14px solid rgb(155, 127, 240);\n"
                                   "}")

    style_btn_clicked_general = (u"QPushButton{\n"
                                 "background-color: rgb(65, 43, 173);\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:hover{\n"
                                 "   background-color: rgb(65, 43, 173);\n"
                                 "   border-left: 14px solid rgb(65, 43, 173);\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "      background-color: rgb(155, 127, 240);\n"
                                 "        border-left: 14px solid rgb(155, 127, 240);\n"
                                 "}")

    style_btn_clicked_home = (u"QPushButton{\n"
                              "background-image: url(:/icons/homeIcon.png);\n"
                              "background-position: left center;\n"
                              "background-repeat: no-repeat;\n"
                              "border: none;\n"
                              "border-left: 14px solid rgb(65, 43, 173);\n"
                              "text-align: left;\n"
                              "padding-left: 45px;\n"
                              "background-color: rgb(65, 43, 173);\n"
                              "}\n"
                              "\n"
                              "QPushButton:hover{\n"
                              "   background-color: rgb(65, 43, 173);\n"
                              "   border-left: 14px solid rgb(65, 43, 173);\n"
                              "}\n"
                              "\n"
                              "QPushButton:pressed {\n"
                              "      background-color: rgb(155, 127, 240);\n"
                              "        border-left: 14px solid rgb(155, 127, 240);\n"
                              "}")
